if(RF_CUDA_FOUND)
  add_executable(cuda_tests test_cuda.cpp)
  target_link_libraries(cuda_tests PRIVATE replicafabric)
  target_include_directories(cuda_tests PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../../test_support")
  target_compile_definitions(cuda_tests PRIVATE REPLICAFABRIC_HAS_CUDA=1)
  target_link_libraries(cuda_tests PRIVATE CUDA::cudart)
  rf_configure_target(cuda_tests)
  add_test(NAME cuda_tests COMMAND cuda_tests)
endif()
