#pragma once

// Replica Fabric self-contained test harness.
//
// Intentionally dependency-free and vendor-neutral: tests register via
// RF_TEST_CASE, assert with RF_CHECK / RF_REQUIRE, and run through a main
// generated by RF_TEST_MAIN. Registration order is deterministic (source order
// of registration). No timeout machinery exists anywhere in this framework or
// in the build; tests run until they pass, fail, crash, or are manually
// terminated after diagnosing a genuine hang.

#include <exception>
#include <functional>
#include <iostream>
#include <sstream>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace rftest {

class TestFailure : public std::exception {
public:
  explicit TestFailure(std::string msg) : msg_(std::move(msg)) {}
  const char* what() const noexcept override { return msg_.c_str(); }
  const std::string& message() const { return msg_; }

private:
  std::string msg_;
};

struct TestCase {
  std::string name;
  std::function<void()> fn;
};

inline std::vector<TestCase>& registry() {
  static std::vector<TestCase> reg;
  return reg;
}

struct Registrar {
  Registrar(const char* name, std::function<void()> fn) {
    registry().push_back(TestCase{std::string(name), std::move(fn)});
  }
};

inline int& failure_count() {
  static int count = 0;
  return count;
}

inline int& current_case_checks() {
  static int checks = 0;
  return checks;
}

inline std::string& current_case_name() {
  static std::string name;
  return name;
}

inline bool& current_case_failed() {
  static bool failed = false;
  return failed;
}

inline void record_failure(const std::string& msg) {
  ++failure_count();
  current_case_failed() = true;
  std::cerr << "  FAIL " << current_case_name() << ": " << msg << "\n";
}

inline void fail(std::string_view cond, std::string_view file, int line) {
  std::ostringstream os;
  os << "CHECK(" << cond << ") failed at " << file << ":" << line;
  record_failure(os.str());
}

inline void check(bool ok, std::string_view cond, std::string_view file, int line) {
  if (!ok) {
    fail(cond, file, line);
  }
}

inline void require(bool ok, std::string_view cond, std::string_view file, int line) {
  if (!ok) {
    fail(cond, file, line);
    throw TestFailure("required check failed");
  }
}

template <typename A, typename B>
void check_eq(const A& a, const B& b, std::string_view aexpr, std::string_view bexpr,
              std::string_view file, int line) {
  if (!(a == b)) {
    std::ostringstream os;
    os << "CHECK_EQ(" << aexpr << ", " << bexpr << ") failed at " << file << ":" << line
       << "  [lhs=" << a << ", rhs=" << b << "]";
    record_failure(os.str());
  }
}

template <typename A, typename B>
void check_ne(const A& a, const B& b, std::string_view aexpr, std::string_view bexpr,
              std::string_view file, int line) {
  if (a == b) {
    std::ostringstream os;
    os << "CHECK_NE(" << aexpr << ", " << bexpr << ") failed at " << file << ":" << line
       << "  [both=" << a << "]";
    record_failure(os.str());
  }
}

inline int run_all(int argc, char** argv) {
  std::string filter;
  bool list_only = false;
  for (int i = 1; i < argc; ++i) {
    const std::string arg = argv[i];
    if (arg == "--list") {
      list_only = true;
    } else if (arg.rfind("--filter=", 0) == 0) {
      filter = arg.substr(9);
    }
  }

  const auto& tests = registry();

  if (list_only) {
    for (const auto& t : tests) {
      std::cout << t.name << "\n";
    }
    return 0;
  }

  int run_count = 0;
  for (auto& t : tests) {
    if (!filter.empty() && t.name.find(filter) == std::string::npos) {
      continue;
    }
    current_case_name() = t.name;
    current_case_checks() = 0;
    current_case_failed() = false;
    const bool was_failed = current_case_failed();
    std::cout << "[ RUN  ] " << t.name << "\n";
    try {
      t.fn();
    } catch (const TestFailure&) {
      // Already recorded by the failing REQUIRE.
    } catch (const std::exception& e) {
      record_failure(std::string("uncaught exception: ") + e.what());
    } catch (...) {
      record_failure("uncaught non-std exception");
    }
    ++run_count;
    if (current_case_failed()) {
      std::cout << "[ FAIL ] " << t.name << "\n";
    } else {
      std::cout << "[ OK   ] " << t.name << "\n";
    }
    (void)was_failed;
  }

  std::cout << "\n";
  if (failure_count() == 0 && run_count > 0) {
    std::cout << "ALL PASSED (" << run_count << " cases)\n";
    return 0;
  }
  std::cout << "FAILURES: " << failure_count() << " across " << run_count << " cases\n";
  return 1;
}

}  // namespace rftest

#define RF_TEST_CASE(name)                                              \
  static void rf_test_fun_##name();                                     \
  static ::rftest::Registrar rf_test_reg_##name(#name, rf_test_fun_##name); \
  static void rf_test_fun_##name()

#define RF_CHECK(cond) ::rftest::check((cond), #cond, __FILE__, __LINE__)

#define RF_REQUIRE(cond) ::rftest::require((cond), #cond, __FILE__, __LINE__)

#define RF_CHECK_EQ(a, b) ::rftest::check_eq((a), (b), #a, #b, __FILE__, __LINE__)
#define RF_CHECK_NE(a, b) ::rftest::check_ne((a), (b), #a, #b, __FILE__, __LINE__)

#define RF_CHECK_THROWS(expr)                                              \
  do {                                                                     \
    bool rf_thrown = false;                                                \
    try {                                                                  \
      (void)(expr);                                                        \
    } catch (...) {                                                        \
      rf_thrown = true;                                                    \
    }                                                                      \
    if (!rf_thrown) {                                                      \
      ::rftest::fail("expected " #expr " to throw", __FILE__, __LINE__);   \
    }                                                                      \
  } while (0)

#define RF_CHECK_NOTHROW(expr)                                             \
  do {                                                                     \
    try {                                                                  \
      (void)(expr);                                                        \
    } catch (const std::exception& e) {                                    \
      ::rftest::fail("expected " #expr " not to throw", __FILE__, __LINE__); \
      std::cerr << "    exception: " << e.what() << "\n";                  \
    } catch (...) {                                                        \
      ::rftest::fail("expected " #expr " not to throw", __FILE__, __LINE__); \
    }                                                                      \
  } while (0)

#define RF_TEST_MAIN()                           \
  int main(int argc, char** argv) {              \
    return ::rftest::run_all(argc, argv);        \
  }
